import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { AiOutlineArrowRight, AiOutlineMail } from 'react-icons/ai'
import Experience from '../components/Experience'
import Projects from '../components/Projects'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Larbi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@200;400;700&display=swap" rel="stylesheet" />
      </Head>
      <main className='bg-black px-10 font-sourceCodePro text-white'>
          <section>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl'>Larbi Belkhit</h1>
              <ul className='flex items-center'>
                <li>
                  <a className='bg-green-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
                </li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-green-500 font-medium'>
                Hello
              </h2>
              <h3 className='text-2xl py-2'>I do my best to code.</h3>
              <p className='text-md py-5 leading-8'>
                I'm an aspiring software engineer based in London. I have great interest in full-stack development, artificial intelligence, data mining, natural language processing, and everything in between.
              </p>
            </div>
            <div className="text-xl flex justify-center">
              <a className='border border-green-500 px-4 py-2 rounded-md text-green-500 flex items-center gap-1' 
                 href="mailto:larbibelkhit@outlook.com" 
                 target="_blank">
                <AiOutlineMail />
                Get in touch
              </a>
            </div>
          </section>
          <section>
            <div className='text-center p-10 mb-2'>
              <h3 className='text-3xl py-1'>About Me</h3>
              <p className='text-md py-2 leading-8'>
                I am currently a <span className='font-bold'>Research Analyst Intern</span> at <span className='font-bold text-green-500'>ABI Research</span>, 
                working on various teams such as AI and Consumer Technology. 
                Simultaneously, I am undertaking a full-time <span className='font-bold'>Bachelor's of Science </span> 
                in <span className='font-bold'>Computer Science</span> at <span className='font-bold text-green-500'>Queen Mary, University of London</span>.
              </p>
              <h4>Here are some technologies I have been working with:</h4>
              <p className='inline-flex gap-2 justify-center items-center'>
                <AiOutlineArrowRight className='text-green-500'/>
                JavaScript ES6+
              </p>
              <p className='flex gap-2 items-center justify-center'>
                <AiOutlineArrowRight className='text-green-500'/>
                React.js</p>
              <p className='flex gap-2 items-center justify-center'>
                <AiOutlineArrowRight className='text-green-500'/>
                Vue.js</p>
              <p className='flex gap-2 items-center justify-center'>
                <AiOutlineArrowRight className='text-green-500'/>
                Python</p>
              <p className='flex gap-2 items-center justify-center'>
                <AiOutlineArrowRight className='text-green-500'/>
                Java</p>
              <p className='flex gap-2 items-center justify-center'>
                <AiOutlineArrowRight className='text-green-500'/>
                HTML & CSS</p>
            </div>
          </section>
          <section>
            <Experience />
          </section>
          <section>
            <Projects />
          </section>
      </main>
    </>
  )
}
