import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Larbi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black px-10'>
          <section>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl'>Larbi Belkhit</h1>
              <ul className='flex items-center'>
                <li>
                  <a className='bg-cyan-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
                </li>
              </ul>
            </nav>
          </section>
      </main>
    </>
  )
}
