import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Larbi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black px-10'>
          <section>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl'>Larbi Belkhit</h1>
              <ul className='flex items-center'>
                <li>
                  <a className='bg-green-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
                </li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-green-500 font-medium'>
                Hello
              </h2>
              <h3 className='text-2xl py-2'>I do my best to code.</h3>
              <p className='text-md py-5 leading-8'>
                I'm an aspiring software engineer based in London. I have great interest in full-stack development, artificial intelligence, data mining, natural language processing, and everything in between.
              </p>
            </div>
            <div className="text-xl flex justify-center">
              <a className='border border-green-500 px-4 py-2 rounded-md text-green-500' 
                 href="mailto:larbibelkhit@outlook.com" 
                 target="_blank">
                Get in touch
              </a>
            </div>
          </section>
      </main>
    </>
  )
}
